name: Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        description: "Select platform to build"
        options:
          - android
          - ios
          - macos
          - windows
          - linux
          - all
        default: "all"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.32.7'
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build android
        if: ${{ github.event.inputs.platform == 'android' || github.event.inputs.platform == 'all' }}
        run: |
          flutter build apk
          echo "Android build completed"

      - name: Build iOS
        if: ${{ github.event.inputs.platform == 'ios' || github.event.inputs.platform == 'all' }}
        run: |
          flutter build ios --release --no-codesign
          echo "iOS build completed"

      - name: Build macOS
        if: ${{ github.event.inputs.platform == 'macos' || github.event.inputs.platform == 'all' }}
        run: |
          flutter build macos
          echo "macOS build completed"

      - name: Build Windows
        if: ${{ github.event.inputs.platform == 'windows' || github.event.inputs.platform == 'all' }}
        run: |
          flutter build windows
          echo "Windows build completed"

      - name: Build Linux
        if: ${{ github.event.inputs.platform == 'linux' || github.event.inputs.platform == 'all' }}
        run: |
          flutter build linux
          echo "Linux build completed"

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter-build-artifacts
          path: |
            build/app/outputs/flutter-apk/
            build/ios/archive/
            build/macos/
            build/windows/
            build/linux/
          if-no-files-found: ignore
