name: Build Flutter iOS

on:
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      # 输出可用模拟器和 SDK
      - name: Show available simulators
        run: |
          xcrun simctl list devices
          xcodebuild -showsdks

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Archive iOS app
        run: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            archive -archivePath build/Runner.xcarchive \
            DEVELOPMENT_TEAM=XXXXXXXXXX CODE_SIGNING_ALLOWED=NO

      - name: Export IPA
        run: |
          cd ios
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist ExportOptions.plist \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: ios/build/ipa/*.ipa
